# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FpgaTool(object):
    def setupUi(self, FpgaTool):
        FpgaTool.setObjectName("FpgaTool")
        FpgaTool.resize(891, 795)
        self.centralWidget = QtWidgets.QWidget(FpgaTool)
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralWidget)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.mdi = QtWidgets.QMdiArea(self.centralWidget)
        self.mdi.setObjectName("mdi")
        self.horizontalLayout.addWidget(self.mdi)
        FpgaTool.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(FpgaTool)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 891, 23))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menuBar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuTools = QtWidgets.QMenu(self.menuBar)
        self.menuTools.setObjectName("menuTools")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuView = QtWidgets.QMenu(self.menuBar)
        self.menuView.setObjectName("menuView")
        FpgaTool.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(FpgaTool)
        self.mainToolBar.setObjectName("mainToolBar")
        FpgaTool.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(FpgaTool)
        self.statusBar.setObjectName("statusBar")
        FpgaTool.setStatusBar(self.statusBar)
        self.actionNew_File = QtWidgets.QAction(FpgaTool)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("pic/newfile.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionNew_File.setIcon(icon)
        self.actionNew_File.setObjectName("actionNew_File")
        self.actionOpen_File = QtWidgets.QAction(FpgaTool)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("pic/openfile.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionOpen_File.setIcon(icon1)
        self.actionOpen_File.setObjectName("actionOpen_File")
        self.actionSave_File = QtWidgets.QAction(FpgaTool)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("pic/savefile.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionSave_File.setIcon(icon2)
        self.actionSave_File.setObjectName("actionSave_File")
        self.actionCascade = QtWidgets.QAction(FpgaTool)
        self.actionCascade.setObjectName("actionCascade")
        self.actionTiled = QtWidgets.QAction(FpgaTool)
        self.actionTiled.setObjectName("actionTiled")
        self.actionView_HDL_Inst = QtWidgets.QAction(FpgaTool)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("pic/gen_inst.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap("pic/text.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionView_HDL_Inst.setIcon(icon3)
        self.actionView_HDL_Inst.setObjectName("actionView_HDL_Inst")
        self.menuFile.addAction(self.actionNew_File)
        self.menuFile.addAction(self.actionOpen_File)
        self.menuFile.addAction(self.actionSave_File)
        self.menuTools.addAction(self.actionView_HDL_Inst)
        self.menuView.addAction(self.actionCascade)
        self.menuView.addAction(self.actionTiled)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuEdit.menuAction())
        self.menuBar.addAction(self.menuView.menuAction())
        self.menuBar.addAction(self.menuTools.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())
        self.mainToolBar.addAction(self.actionNew_File)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actionOpen_File)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actionSave_File)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actionView_HDL_Inst)

        self.retranslateUi(FpgaTool)
        QtCore.QMetaObject.connectSlotsByName(FpgaTool)

    def retranslateUi(self, FpgaTool):
        _translate = QtCore.QCoreApplication.translate
        FpgaTool.setWindowTitle(_translate("FpgaTool", "MainWindow"))
        self.menuFile.setTitle(_translate("FpgaTool", "File"))
        self.menuEdit.setTitle(_translate("FpgaTool", "Edit"))
        self.menuTools.setTitle(_translate("FpgaTool", "Tools"))
        self.menuHelp.setTitle(_translate("FpgaTool", "Help"))
        self.menuView.setTitle(_translate("FpgaTool", "View"))
        self.actionNew_File.setText(_translate("FpgaTool", "New File"))
        self.actionNew_File.setShortcut(_translate("FpgaTool", "Ctrl+N"))
        self.actionOpen_File.setText(_translate("FpgaTool", "Open File"))
        self.actionOpen_File.setShortcut(_translate("FpgaTool", "Ctrl+O"))
        self.actionSave_File.setText(_translate("FpgaTool", "Save File"))
        self.actionSave_File.setShortcut(_translate("FpgaTool", "Ctrl+S"))
        self.actionCascade.setText(_translate("FpgaTool", "Cascade"))
        self.actionTiled.setText(_translate("FpgaTool", "Tiled"))
        self.actionView_HDL_Inst.setText(_translate("FpgaTool", "View HDL Inst"))

